### ISSUE TITLE
Feedback and small issues

### ISSUE THREAD

**Issue by CGMossa** [picklenerd/pngme_book#1]
Hey! I love this little book/exercise. I'm trying to follow it. 

Chapter 1 is missing an:
> Required methods:
> 1. `fn is_err(&self)-> bool`

I'll write more as I progress through it.

Very cool!

**Comment by picklenerd** [comment]
Glad you're enjoying it!

One of the unit tests had an `unwrap` that shouldn't have been there. The test thought it was checking a `Result` with `is_err` but it was really looking at a `ChunkType` and failing.

I just merged a PR that should fix this:
https://github.com/picklenerd/pngme_book/pull/2

**Comment by CGMossa** [comment]
Thanks again for the book.. I am stuck on something obscure, but I'll ask someone to help with it more closely. Thanks for addressing my feedback! That's beyond cool of you. Closing this

**Comment by picklenerd** [comment]
What are you stuck on?
