### ISSUE TITLE
Chunk missing constructor requirement

### ISSUE THREAD

**Issue by MMDF** [picklenerd/pngme_book#6]
Hey! Thanks for this awesome book.
I found a small missing part in Chapter 2(Chunks)

This function is used in the Png unit tests without ever being talked about inside of Chunks:
```rust
    pub fn new(chunk_type: ChunkType, data: Vec<u8>) -> Chunk
```
You should consider adding it to Chapter 2's requirements

**Comment by MMDF** [comment]
It seems this function exists in the given source code but I didn't know there was such source code until I searched for this github repo

**Comment by wgaffa** [comment]
I would like to see a test for this if since it's used in the png tests as well. I'd argue that since the user is supposed to work through the code without looking up the source code (unless the user is stuck perhaps) I'd like a bulletin point to ask to create this function and have a test for it.

**Comment by picklenerd** [comment]
I added a requirement for a `new` function along with a test to check that it works. Thanks for reporting this!
