### ISSUE TITLE
crc api changed

### ISSUE THREAD

**Issue by wgaffa** [picklenerd/pngme_book#7]
I added the crc crate given in Chapter 2 as a hint but it seemed they have a different api than when this was written.
My suggestion is to either specify that they should use a specific crc crate version, or update the chapter to reflect the new api changes.

**Comment by MMDF** [comment]
Yeah, I figured the specific version from the linked documentation: https://docs.rs/crc/1.8.1/crc/crc32/fn.checksum_ieee.html but it makes sense that it is added.

**Comment by picklenerd** [comment]
I updated the link to point to the 2.1.0 api. Thanks!
