### ISSUE TITLE
A question about the test for `is_valid` in Chapter 1

### ISSUE THREAD

**Issue by makisevon** [picklenerd/pngme_book#8]
```rust
#[test]
pub fn test_valid_chunk_is_valid() {
    let chunk = ChunkType::from_str("RuSt").unwrap();
    assert!(chunk.is_valid());
}

#[test]
pub fn test_invalid_chunk_is_valid() {
    let chunk = ChunkType::from_str("Rust").unwrap();
    // according to the hint, a successfully constructed `ChunkType` should always be valid
    assert!(!chunk.is_valid());

    let chunk = ChunkType::from_str("Ru1t");
    assert!(chunk.is_err());
}
```

Seems like `is_valid` and `is_reserved_bit_invalid` are equivalent, I'm not sure if I've misunderstood something. qaq

**Comment by picklenerd** [comment]
For the tests, there's definitely a lot of overlap here. The individual bit tests are just checking that you implemented the spec properly and making sure you get test failures that point to the exact bit you got wrong.

For the implementation, `is_reserved_bit_invalid` should check that the third bit is valid whereas `is_valid` should check that all four bits are valid.

**Comment by makisevon** [comment]
Clear, thx ~
